
FROM python:3.12-slim


WORKDIR /app


COPY requirements.txt .


RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


COPY server ./server
COPY models ./models


EXPOSE 8000


CMD uvicorn server.main:app --host 0.0.0.0 --port 8000 
