FROM python:3.12-slim


WORKDIR /app


COPY requirements.txt .


RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


COPY inference ./inference
COPY models ./models
COPY reports ./reports

EXPOSE 8501


CMD streamlit run inference/app.py --server.port=8501 --server.address=0.0.0.0
